# This action runs a python script that generates a .tex file which thanks contributors and several more that clean up files.
# This action then compiles each main.tex document and pushes all the documents in one commit.

name: Clean and Compile

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs run in parallel
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Use python to automate generating some .tex files
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Make Contributors List
        run: |
          python make_contributors.py

      - name: Cleanup Files
        run: |
          python clean_equations.py
          python clean_quotes.py

      # Compile calculus work
      - name: Compile Calculus
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          working_directory: ./calc

      # Compile multivariable calculus work
      - name: Compile Multivariable Calculus
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          working_directory: ./multiCalc

      # Compile diffeq work
      - name: Compile DiffEq
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          working_directory: ./diffEq

      # Push all compiled documents
      - name: Commit Files
        run: |
          git config --global user.name 'Github Actions [BOT]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m "Compile LaTeX files" -a

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
